USE [ProjectWebApp_Prod]
GO

SELECT [AssignmentUID]
      ,[TimeByDay]
      ,[ProjectUID]
      ,[TaskUID]
      ,[AssignmentCost]
      ,[AssignmentOvertimeCost]
      ,[AssignmentActualCost]
      ,[AssignmentActualOvertimeCost]
      ,[AssignmentWork]
      ,[AssignmentOvertimeWork]
      ,[AssignmentActualWork]
      ,[AssignmentActualOvertimeWork]
      ,[AssignmentMaterialWork]
      ,[AssignmentMaterialActualWork]
      ,[AssignmentBudgetCost]
      ,[AssignmentBudgetWork]
      ,[AssignmentBudgetMaterialWork]
      ,[AssignmentResourcePlanWork]
      ,[TaskIsActive]
      ,[AssignmentRegularCost]
      ,[AssignmentRemainingCost]
      ,[AssignmentRemainingOvertimeCost]
      ,[AssignmentActualRegularCost]
      ,[AssignmentRemainingRegularCost]
      ,[AssignmentRegularWork]
      ,[AssignmentRemainingWork]
      ,[AssignmentRemainingOvertimeWork]
      ,[AssignmentActualRegularWork]
      ,[AssignmentRemainingRegularWork]
      ,[AssignmentCombinedWork]
      ,[AssignmentCount]
      ,[AssignmentBaseline0Cost]
      ,[AssignmentBaseline0Work]
      ,[AssignmentBaseline0MaterialWork]
      ,[AssignmentBaseline0BudgetCost]
      ,[AssignmentBaseline0BudgetWork]
      ,[AssignmentBaseline0BudgetMaterialWork]
      
  FROM [dbo].[MSP_EpmAssignmentByDay_UserView]
GO


