USE [ProjectWebApp_Prod]
GO

SELECT distinct [ProjectUID]
      ,[ResourceUID]
      ,[TaskUID]
      ,[TimesheetClassUID]
      ,[ResourceOwnerUID]
      ,[AssignmentBookingID]
      ,[AssignmentType]
      ,[AssignmentResourceType]
      ,[AssignmentUID]
      ,[AssignmentCost]
      ,[AssignmentOvertimeCost]
      ,[AssignmentActualCost]
      ,[AssignmentActualOvertimeCost]
      ,[AssignmentWork]
      ,[AssignmentOvertimeWork]
      ,[AssignmentActualWork]
      ,[AssignmentActualOvertimeWork]
      ,[AssignmentMaterialWork]
      ,[AssignmentMaterialActualWork]
      ,[AssignmentPercentWorkCompleted]
      ,[AssignmentStartDate]
      ,[AssignmentFinishDate]
      ,[AssignmentActualStartDate]
      ,[AssignmentActualFinishDate]
      ,[AssignmentDelay]
      ,[AssignmentStartVariance]
      ,[AssignmentFinishVariance]
      ,[AssignmentACWP]
      ,[AssignmentBCWP]
      ,[AssignmentBCWS]
      ,[AssignmentIsPublished]
      ,[IsPublic]
      ,[AssignmentCostVariance]
      ,[AssignmentWorkVariance]
      ,[AssignmentCV]
      ,[AssignmentSV]
      ,[AssignmentVAC]
      ,[AssignmentIsOverallocated]
      ,[AssignmentPeakUnits]
      ,[AssignmentCreatedRevisionCounter]
      ,[AssignmentModifiedRevisionCounter]
      ,[AssignmentCreatedDate]
      ,[AssignmentModifiedDate]
      ,[AssignmentBudgetCost]
      ,[AssignmentBudgetWork]
      ,[AssignmentBudgetMaterialWork]
      ,[AssignmentResourcePlanWork]
      ,[TaskIsActive]
      ,[AssignmentRegularCost]
      ,[AssignmentRemainingCost]
      ,[AssignmentRemainingOvertimeCost]
      ,[AssignmentActualRegularCost]
      ,[AssignmentRemainingRegularCost]
      ,[AssignmentRegularWork]
      ,[AssignmentRemainingWork]
      ,[AssignmentRemainingOvertimeWork]
      ,[AssignmentActualRegularWork]
      ,[AssignmentRemainingRegularWork]
      ,[AssignmentCount]
      ,[AssignmentBaseline0Cost]
      ,[AssignmentBaseline0Work]
      ,[AssignmentBaseline0MaterialWork]
      ,[AssignmentBaseline0BudgetCost]
      ,[AssignmentBaseline0BudgetWork]
      ,[AssignmentBaseline0BudgetMaterialWork]
      ,[AssignmentBaseline0StartDate]
      ,[AssignmentBaseline0FinishDate]
      ,[AssignmentBaseline1Cost]
      ,[AssignmentBaseline1Work]
      ,[AssignmentBaseline1MaterialWork]
      ,[AssignmentBaseline1BudgetCost]
      ,[AssignmentBaseline1BudgetWork]
      ,[AssignmentBaseline1BudgetMaterialWork]
      ,[AssignmentBaseline1StartDate]
      ,[AssignmentBaseline1FinishDate]
      ,[AssignmentBaseline2Cost]
      ,[AssignmentBaseline2Work]
      ,[AssignmentBaseline2MaterialWork]
      ,[AssignmentBaseline2BudgetCost]
      ,[AssignmentBaseline2BudgetWork]
      ,[AssignmentBaseline2BudgetMaterialWork]
      ,[AssignmentBaseline2StartDate]
      ,[AssignmentBaseline2FinishDate]
      ,[AssignmentBaseline3Cost]
      ,[AssignmentBaseline3Work]
      ,[AssignmentBaseline3MaterialWork]
      ,[AssignmentBaseline3BudgetCost]
      ,[AssignmentBaseline3BudgetWork]
      ,[AssignmentBaseline3BudgetMaterialWork]
      ,[AssignmentBaseline3StartDate]
      ,[AssignmentBaseline3FinishDate]
      ,[AssignmentBaseline4Cost]
      ,[AssignmentBaseline4Work]
      ,[AssignmentBaseline4MaterialWork]
      ,[AssignmentBaseline4BudgetCost]
      ,[AssignmentBaseline4BudgetWork]
      ,[AssignmentBaseline4BudgetMaterialWork]
      ,[AssignmentBaseline4StartDate]
      ,[AssignmentBaseline4FinishDate]
      ,[AssignmentBaseline5Cost]
      ,[AssignmentBaseline5Work]
      ,[AssignmentBaseline5MaterialWork]
      ,[AssignmentBaseline5BudgetCost]
      ,[AssignmentBaseline5BudgetWork]
      ,[AssignmentBaseline5BudgetMaterialWork]
      ,[AssignmentBaseline5StartDate]
      ,[AssignmentBaseline5FinishDate]
      ,[AssignmentBaseline6Cost]
      ,[AssignmentBaseline6Work]
      ,[AssignmentBaseline6MaterialWork]
      ,[AssignmentBaseline6BudgetCost]
      ,[AssignmentBaseline6BudgetWork]
      ,[AssignmentBaseline6BudgetMaterialWork]
      ,[AssignmentBaseline6StartDate]
      ,[AssignmentBaseline6FinishDate]
      ,[AssignmentBaseline7Cost]
      ,[AssignmentBaseline7Work]
      ,[AssignmentBaseline7MaterialWork]
      ,[AssignmentBaseline7BudgetCost]
      ,[AssignmentBaseline7BudgetWork]
      ,[AssignmentBaseline7BudgetMaterialWork]
      ,[AssignmentBaseline7StartDate]
      ,[AssignmentBaseline7FinishDate]
      ,[AssignmentBaseline8Cost]
      ,[AssignmentBaseline8Work]
      ,[AssignmentBaseline8MaterialWork]
      ,[AssignmentBaseline8BudgetCost]
      ,[AssignmentBaseline8BudgetWork]
      ,[AssignmentBaseline8BudgetMaterialWork]
      ,[AssignmentBaseline8StartDate]
      ,[AssignmentBaseline8FinishDate]
      ,[AssignmentBaseline9Cost]
      ,[AssignmentBaseline9Work]
      ,[AssignmentBaseline9MaterialWork]
      ,[AssignmentBaseline9BudgetCost]
      ,[AssignmentBaseline9BudgetWork]
      ,[AssignmentBaseline9BudgetMaterialWork]
      ,[AssignmentBaseline9StartDate]
      ,[AssignmentBaseline9FinishDate]
      ,[AssignmentBaseline10Cost]
      ,[AssignmentBaseline10Work]
      ,[AssignmentBaseline10MaterialWork]
      ,[AssignmentBaseline10BudgetCost]
      ,[AssignmentBaseline10BudgetWork]
      ,[AssignmentBaseline10BudgetMaterialWork]
      ,[AssignmentBaseline10StartDate]
      ,[AssignmentBaseline10FinishDate]
      ,[RBS_R]
      ,[Health_T]
      ,[Flag Status_T]
      ,[Cost Type_R]
      ,[Resource Departments_R]
      ,[CHOC Resource Type_R]
      ,[Job Title_R]
      ,[Resource Manager_R]
      ,[Major Milestone_T]
      ,[Go Live Date_T]
      ,[Schedule Health Task_T]
      ,[Status Notes_T]
  FROM [dbo].[MSP_EpmAssignment_UserView]
GO


