CREATE PROCEDURE Three_Year_Kronos
AS

SELECT        APPLYDATE
			, PAYCODENAME
			, SUM(TIMEINSECONDS) / 60 AS MinutesWorked
			, PERSONNUM
			, PERSONFULLNAME
			, LABORLEVELNAME2 AS position
			, LABORLEVELDSC2 AS title
			, PAYCODEID
			, PERSONID
			/*, CURRPAYPERIODSTART
			, CURRPAYPERIODEND
			, PREVPAYPERIODSTART
			, PREVPAYPERIODEND*/
into dbo.[Kronos_3_Year_to_present]
FROM            [CHOCNT-097].wfcdb.dbo.VP_TOTALS AS VP_TOTALS_1
WHERE       PERSONNUM IN (select distinct [EE#] from dbo.['Position_Staff - Coder$'])
			AND (PAYCODETYPE = 'P') AND (PAYCODENAME <> 'Previous Pay Period Approved') 
			AND (PAYCODENAME <> '12HRDT-1') 
			AND cast([APPLYDATE]as date) > '2011'
			AND cast([APPLYDATE]as date) < cast(getdate() as date)
			--AND (APPLYDATE BETWEEN PREVPAYPERIODSTART AND CURRPAYPERIODEND)
GROUP BY APPLYDATE, PAYCODENAME, TIMEINSECONDS, PERSONNUM, PERSONFULLNAME, LABORLEVELNAME2, LABORLEVELDSC2, PAYCODEID, PERSONID, 
                         CURRPAYPERIODSTART, CURRPAYPERIODEND, PREVPAYPERIODSTART, PREVPAYPERIODEND


GO