SELECT [Productivity_Report].[dbo].[KronosExpanded].[APPLYDATE]
      ,[Productivity_Report].[dbo].[KronosExpanded].[PAYCODENAME]
      ,[Productivity_Report].[dbo].[KronosExpanded].[KPAYCODE]
	  ,[Productivity_Report].[dbo].['Pay Code & Desc$'].[DESCRIPTION]
      ,[Productivity_Report].[dbo].[KronosExpanded].[HoursWorked]
      ,[Productivity_Report].[dbo].[KronosExpanded].[PAYCODEID]
      ,[Productivity_Report].[dbo].[KronosExpanded].[PERSONNUM]
      ,[Productivity_Report].[dbo].[KronosExpanded].[PERSONFULLNAME]
      ,[Productivity_Report].[dbo].[KronosExpanded].[position]
      ,[Productivity_Report].[dbo].[KronosExpanded].[Cost Center]
      ,[Productivity_Report].[dbo].[KronosExpanded].[PL]
      ,[Productivity_Report].[dbo].[KronosExpanded].[DeptNum]
	  ,[Productivity_Report].[dbo].[Dept$].[DEPARTMENT]
      ,[Productivity_Report].[dbo].[KronosExpanded].[Job Code]
      ,[Productivity_Report].[dbo].[KronosExpanded].[title]
      ,[Productivity_Report].[dbo].[KronosExpanded].[PERSONID]
  FROM [Productivity_Report].[dbo].[KronosExpanded]
  LEFT JOIN [Productivity_Report].[dbo].[Dept$]
  ON [Productivity_Report].[dbo].[KronosExpanded].[DeptNum] = [Productivity_Report].[dbo].[Dept$].[DEPT #]
  Left JOIN [Productivity_Report].[dbo].['Pay Code & Desc$']
  ON [Productivity_Report].[dbo].[KronosExpanded].[KPAYCODE] = [Productivity_Report].[dbo].['Pay Code & Desc$'].[PAY_CODE]
  WHERE [Productivity_Report].[dbo].[KronosExpanded].[APPLYDATE] > DATEADD(DAY,-1,GETDATE())