SELECT  [Productivity].[dbo].[PayCode_OT1_Sum].[PERSONFULLNAME]
      ,[Productivity].[dbo].[PayCode_OT1_Sum].[PERSONNUM]
	  ,[Productivity].[dbo].[PayCode_OT1_Sum].[Total OT]
      ,[Productivity].[dbo].[PayCode_REG-1_Sum].[Total REG-1]
	  ,[Productivity].[dbo].[PayCode_Reg-2_Sum].[Total REG-2]
	  FROM [Productivity].[dbo].[PayCode_OT1_Sum]
	  Left join [Productivity].[dbo].[PayCode_REG-1_Sum]
	  ON [Productivity].[dbo].[PayCode_OT1_Sum].[PERSONNUM]=[Productivity].[dbo].[PayCode_REG-1_Sum].[PERSONNUM]
	  Left JOIN [Productivity].[dbo].[PayCode_Reg-2_Sum]
	  ON [Productivity].[dbo].[PayCode_OT1_Sum].[PERSONNUM]=[Productivity].[dbo].[PayCode_Reg-2_Sum].[PERSONNUM]