SELECT DISTINCT [PERSONNUM]
	  ,[PAYCODENAME]
	  ,[APPLYDATE]
      ,SUM([MinutesWorked])
  FROM [Productivity_Report].[dbo].[Kronos_Alternative]
  WHERE [PERSONID] IN (SELECT  DISTINCT [PERSONID] FROM [Productivity_Report].[dbo].[3M_Coder_Kronos]) 
  AND [APPLYDATE] <= getdate()
  AND getdate() BETWEEN [PREVPAYPERIODSTART] AND [CURRPAYPERIODEND]
  AND [APPLYDATE] BETWEEN [PREVPAYPERIODSTART] AND [CURRPAYPERIODEND]
  
  GROUP BY [PERSONNUM],[PAYCODENAME],[APPLYDATE]